# SPDX-FileCopyrightText: 2024 Tillitis AB <tillitis.se>
# SPDX-License-Identifier: BSD-2-Clause
version = 1

[[annotations]]
path = ".github/workflows/*"
SPDX-FileCopyrightText = "2022 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
     ".clang-format",
     ".editorconfig",
     ".gitignore",
     "Makefile",
     "README.md",
     "RELEASE.md",
     "docs/implementation-notes.md",
     "signer/app.bin.sha512"
]
SPDX-FileCopyrightText = "2022 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "BSD-2-Clause"
